### ISSUE TITLE
DailyFilings not working

### ISSUE THREAD

**Issue by jonzd** [sec-edgar/sec-edgar#116]
Using the DailyFilings function to get a day's filings does not work, Line 92 of daily.py has a problem with datetime.strftime.

TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'str'

When I changed datetime.datetime.strftime to formatted_date = self._date.strftime("%y%m%d"), network_client.py gives a client-side error.

Thanks!

**Comment by jackmoody11** [comment]
Thanks for reporting this bug. Can you give the full traceback?

**Comment by jonzd** [comment]
---------------------------------------------------------------------------
EDGARQueryError                           Traceback (most recent call last)
~\anaconda3\lib\site-packages\secedgar\client\network_client.py in get_response(self, path, params, **kwargs)
     96             try:
---> 97                 self._validate_response(response)
     98             except EDGARQueryError:

~\anaconda3\lib\site-packages\secedgar\client\network_client.py in _validate_response(response)
    138             else:
--> 139                 raise EDGARQueryError("The query could not be completed. "
    140                                       "There was a client-side error with your "

EDGARQueryError: An error occured while making the query.

During handling of the above exception, another exception occurred:

EDGARQueryError                           Traceback (most recent call last)
<ipython-input-3-6440b2e0f865> in <module>
----> 1 today_filings.save(os.getcwd())

~\anaconda3\lib\site-packages\secedgar\filings\daily.py in save(self, directory)
    191                 further by company name and form type.
    192         """
--> 193         self.get_filings_dict()
    194         for filings in self._filings_dict.values():
    195             # take the company name from the first filing and make that the subdirectory name

~\anaconda3\lib\site-packages\secedgar\filings\daily.py in get_filings_dict(self, update_cache, **kwargs)
    131         """
    132         if self._filings_dict is None or update_cache:
--> 133             idx_file = self._get_master_idx_file(**kwargs)
    134             # Will have CIK as keys and list of FilingEntry namedtuples as values
    135             self._filings_dict = {}

~\anaconda3\lib\site-packages\secedgar\filings\daily.py in _get_master_idx_file(self, update_cache, **kwargs)
     91             formatted_date = self._date.strftime("%y%m%d")
     92             formatted_file_name = "master.{date}.idx".format(date=formatted_date)
---> 93             if formatted_file_name in self._get_quarterly_directory().text:
     94                 master_idx_url = "{path}/master.{date}.idx".format(
     95                     path=self.path, date=formatted_date)

~\anaconda3\lib\site-packages\secedgar\filings\daily.py in _get_quarterly_directory(self, update_cache, **kwargs)
     70         """
     71         if self._quarterly_directory is None or update_cache:
---> 72             self._quarterly_directory = self.client.get_response(self.path, self.params, **kwargs)
     73         return self._quarterly_directory
     74 

~\anaconda3\lib\site-packages\secedgar\client\network_client.py in get_response(self, path, params, **kwargs)
    100                 # Raise query error if on last retry
    101                 if i == self.retry_count:
--> 102                     raise EDGARQueryError()
    103         self.response = response
    104         return self.response

EDGARQueryError: An error occured while making the query.

**Comment by jackmoody11** [comment]
@jonzd thanks for providing the details. I won’t be able to fix this bug until the end of June, but will look into what is causing it and get it fixed as soon as possible. I appreciate your support!

**Comment by jackmoody11** [comment]
@jonzd can you show the code where you create `todays_filings`?

**Comment by jonzd** [comment]
@jackmoody11 
`today_filings = DailyFilings(date=datetime(2020,6,10))`

**Comment by jackmoody11** [comment]
@jonzd I had a chance to look at the code. There are a few changes I am working on. It throws an EDGARQueryError after fixing `strftime` because the path requires a trailing slash.

```python
    @property
    def path(self):
        """str: Path added to client base.

        .. note::
           The trailing slash at the end of the path is important.
           Omitting will raise EDGARQueryError.
        """
        return "Archives/edgar/daily-index/{year}/QTR{num}/".format(
            year=self._date.year, num=self.quarter)
```

**Comment by jackmoody11** [comment]
## Note

The format for master.idx files changes some time in the 90's or 2000's. Will need to adapt code to take care of this. Currently causes a bug.

**Comment by jackmoody11** [comment]
@jonzd this bug should be fixed now. If you can confirm that the latest version of the master branch fixes your problem that would be much appreciated! Thanks for helping improve the project. Your name is mentioned in our v0.1.7 docs.
