### ISSUE TITLE
Missing fillings on request, provided cik, information gaps

### ISSUE THREAD

**Issue by Marsh-James** [sec-edgar/sec-edgar#117]
**Describe the bug**
Using the generic code you provide, I'm requesting 10-k and 10-q filings. Unfortunately I'm only receiving information up to 2009 (where there is a format change but the filing is consistent), and missing years 2016. 

**To Reproduce**
Steps to reproduce the behaviour:

```python
company_ciks = {
    'alphabet': ['0001288776', '0001652044']
}

dir_path = '_dataset/'

requests_counter = 0
for company_name, ciks in company_ciks.items():
    company_path = dir_path + company_name
    
    for cik in ciks:
        requests_counter += 1

        my_filings = Filing(cik_lookup=cik, filing_type=FilingType.FILING_10Q)
        my_filings.save(company_path)
        
        print('\rCompleted ' + str(requests_counter) + ' requests...', end='')
        sleep(1)

print('\nObtained all 10Q filings...')
```

I've attached my code to demonstrate how my fillings are being pulled. Just wrapped in some loops nothing fancy. Yet we still miss information that is available.

Here are the filings for the first cik, showing them going back to 2005.
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001288776&type=10-q&dateb=&owner=exclude&count=40

I have a feeling it could be timed out information, I'm going to try pull all the data again to see. I'm aware edgar has a 10 request per second limit which might cause some throttling and timeouts.

Really love sec-edgar, keep up the great work! :)

**Comment by jackmoody11** [comment]
Thanks for filing an issue @Marsh-James! I will look into it.

**Comment by Marsh-James** [comment]
Hi, cheers for the reply. Also had a look at the code in [filing.py](https://github.com/sec-edgar/sec-edgar/blob/master/secedgar/filings/filing.py), I think you're right. Running the test now. I'll update when I have the results :).

**Comment by Marsh-James** [comment]
Had a crack, fell into another error. Still saved more files than 10 this time. 
![image](https://user-images.githubusercontent.com/32681425/85881065-f59edb80-b7d4-11ea-956e-ae06f20a9166.png)

**Comment by Marsh-James** [comment]
Fixed by adding encoding format see line 213:
![image](https://user-images.githubusercontent.com/32681425/85884309-554bb580-b7da-11ea-979d-c9191bc5d856.png)

**Comment by jackmoody11** [comment]
@Marsh-James did you completely solve the problems you were having? If so, I think all that needs to be done is make the `Filing` object save all filings that it finds by default.

**Comment by jackmoody11** [comment]
TODO:

- Rename `count` variable used in `Filing` class to signify total number of filings to fetch
- Rename `count` variable used in `NetworkClient` to signify batch size to fulfill requests in (ex: `count = 10` means fetch 10 filings at a time)

**Comment by Marsh-James** [comment]
> @Marsh-James did you completely solve the problems you were having? If so, I think all that needs to be done is make the `Filing` object save all filings that it finds by default.

Yeah, so the fix was to expand count to include more files than the default 10, and then for some reason one of the 10-Q reports contained latin-1 characters which we're given trouble when encoding. I modified the save file to specify utf-8 which then solved that problem. So far I can't see any side effects, I'll update if something comes up. :)

**Comment by jackmoody11** [comment]
> Edit:
> If possible it would be really useful to download all files if nothing is specified, I'm sure it's possible when scanning master files. I could take a look at proposing a solution for you but I'm sure you're more experienced in this than I am.

I was thinking the exact same thing. I will start working on this. Should be a simple fix.
