### ISSUE TITLE
missing forms do not generate error's if years pulled are less 

### ISSUE THREAD

**Issue by rahul18cracker** [sec-edgar/sec-edgar#124]
Hi Jack 

Thanks a lot for your help in advance, i took the latest package of secedgar 0.1.7 today(previously i was on 0.1.6. I was trying to pull 10-k forms for various companies and things were working good. I was able to pull a few companies but when i pull the symbol 'dis' for 10 years of records i see only 2019 file. Then i check secedgar page and it only show results for 2019. The question i have is that can some error handling or reporting be added to the API's to say that n number if years were not fetched and only x years were fetched ?

eg
```Python
my_filings = Filing(cik_lookup='dis', filing_type=FilingType.FILING_10K, count=10)
my_filings.save('/Users/folder-to-save-on-my-local-disk')
```

In case you have more questions please let me know. I have subscribed this repo 

Thanks
~Rahul

**Comment by jackmoody11** [comment]
@rahul18cracker thanks for sharing this. That sounds like a good idea and should not be too difficult to implement. I’ll work on adding a warning for v0.2.0.
