### ISSUE TITLE
ModuleNotFoundError 'click'

### ISSUE THREAD

**Issue by jasontwright** [sec-edgar/sec-edgar#135]
**Describe the bug**
ModuleNotFoundError 'click'

**To Reproduce**
1. Executed `secedgar daily --date 20200824` on a Windows machine running Python 3.7.1
2. Error follows:
`Traceback (most recent call last):`
  `File "c:\users\jwright\python37_64bit\lib\runpy.py", line 193, in _run_module_as_main"__main__", mod_spec)`
  `File "c:\users\jwright\python37_64bit\lib\runpy.py", line 85, in _run_code exec(code, run_globals)`
  `File "C:\Users\jwright\Python37_64bit\Scripts\secedgar.exe\__main__.py", line 4, in <module>`
  `File "c:\users\jwright\python37_64bit\lib\site-packages\secedgar\cli.py", line 1, in <module> import click`
`ModuleNotFoundError: No module named 'click'`
3. I am an admittedly a VERY new user of Python so apologize if this is an easy fix

**Comment by jackmoody11** [comment]
Thanks for raising this issue @jasontwright! I need to put this in the documentation. Currently, the CLI is an optional install, meaning that the extra dependency needed for it (called click), is not installed by default.

To install the secedgar package with dependencies for the CLI, use the following:

```
pip install secedgar[cli]
```

For future reference, it also should work to just `pip install click`. If a `ModuleNotFoundError` is raised and it isn't a module from your own code, you can typically fix it with `pip install <missing_module_name>`.
