### ISSUE TITLE
Daily filings with DailyFilings class all have "404 - Not Found" content

### ISSUE THREAD

**Issue by alpbozkurt** [sec-edgar/sec-edgar#136]
**Describe the bug**
With DailyFilings usage, 'save_filings' method of IndexFilings class generates wrong URLs for calls to 'requests.get', which results in "404 - Not Found" page in all downloaded files. I.e: URL: http://www.sec.gov/0001140361-20-015873.txt

Interstingly, 'get_urls' method generates correct URL list but 'save_filings' method don't use it and generates URLs in some other way, which is wrong.

Also, the accompanying tests don't check the downloaded content, so 404 page content is not caught by those tests.

**To Reproduce**
1. filings_client = DailyFilings(date)
2. filings_client.get_urls() # correct URLs listed
3. filings_client.save(folder) # All files have 404 page content

**Expected behavior**
'save' method for DailyFilings should generate correct URLs and download filings, not 404 page content.

**Possible Fix**
In 'save_filings' method of 'IndexFilings' class:

<< url = self.make_url(filename)

>> archive_filename = "Archives/%s" % filing.file_name # may not work with Python < 3 ?
>> url = self.make_url(archive_filename)

Tested this in Python 3.8

A better fix might be the use of 'get_urls' the way 'Filing.save' method does.

I can create a PR for whichever way you choose.

**Desktop (please complete the following information):**
Ubuntu 20.04

**Comment by jackmoody11** [comment]
Thanks for bringing this up @alpbozkurt! If you want to mirror how we took care of this with the Filing object that would be awesome. If not, I can also fix it.
