### ISSUE TITLE
PF Filing Type Not Returning Any Results

### ISSUE THREAD

**Issue by baridhi** [sec-edgar/sec-edgar#141]
I tried using the library to get form PF. However, I get an error.
More generally, may I request you to please share which repository/SEC archive do you use to extract from PF?
I'm particularly interested in that data on hedge funds. Thanks.

**Comment by jackmoody11** [comment]
@baridhi can you please share the snippet of code that is giving you an error and also paste the trace back so I can see where the error is coming from? I will look into this.

**Comment by baridhi** [comment]
Hi Jack, thanks a lot for the message. I realized it was a trivial mistake at my end. So the package worked for say, form 13D etc. But I'm more keen on form PF and tried this for Blackstone (using blk as ticker). But it does not recover any info. Am I missing something? Elsewhere, I did learn that form PF is regulatory data and may not be disclosed by the SEC. I'm unsure of how to reconcile that with how your package allows for form PF as well. PFA a screenshot. And apologies in case my query is misguided.
![secEdgar_error](https://user-images.githubusercontent.com/30325396/98451061-5c7fba00-2110-11eb-8b01-01a30bd4cd60.png)

**Comment by jackmoody11** [comment]
@baridhi I looked for Blackrock's PF filings through SEC Edgar and didn't find anything. You might want to check if there are subsidiaries of Blackrock that are required to file PF filings that use different CIKs.  You can see my search for Blackrock's PF filings here:

![Blackrock PF Filing search](https://user-images.githubusercontent.com/27718962/98454407-33702100-2132-11eb-9231-1ab6a130da02.png)

Admittedly, using a company's ticker isn't the perfect way to find all of a company's filings for this reason. Your best bet is to locate the correct CIKs for the companies you are interested in and use that when fetching the filings. If after finding the correct CIK, you are still unable to download the filings, please let me know and I will work on a bug fix. I think this is an issue that is worth putting in the documentation in the future and I appreciate you taking the time to let me know about it!

**Comment by jackmoody11** [comment]
TODO

- [ ]  Add test to check that non-existent ticker raises `CIKError` rather than `ValueError` when no URLs returned

**Comment by baridhi** [comment]
Hi Jack, Thanks a lot for the helpful pointers. I read up more on this, and found this: https://www.sec.gov/files/formpf.pdf . As per page 11 on this, the SEC does not intend to make available form PF (filed by private funds, not publicly listed) information. So we should not be able to find those details anywhere. Except with the SEC themselves. So perhaps your library works just fine and maybe the modification you plan to incorporate on the error message might indeed be helpful. Thanks again!

**Comment by jackmoody11** [comment]
@baridhi Thanks for letting me know. It seems like that is the case. I may add removing the PF filing type to the to do list as well.
