### ISSUE TITLE
Form 13G and 13D

### ISSUE THREAD

**Issue by nmccarthy82** [sec-edgar/sec-edgar#151]
I would like to be able to pull forms SC-13G, SC-13D, SC-13G\A and SC-13D\A

**Comment by jackmoody11** [comment]
@nmccarthy82 would you mind providing a company or two that would have these filings for testing purposes?

**Comment by nmccarthy82** [comment]
@jackmoody11 
JOHNSON & JOHNSON (JNJ) (CIK 0000200406)
Enphase Energy, Inc. (ENPH) (CIK 0001463101)

**Comment by jackmoody11** [comment]
Ok, @nmccarthy82 this is an easy fix. I am currently working on  #150 which is a much larger PR and will lump this change in with those changes. All I need to do over there is add testing.
