### ISSUE TITLE
Form ABS-EE

### ISSUE THREAD

**Issue by statzhero** [sec-edgar/sec-edgar#153]
I'm making a request for form ABS-EE, in particular Exhibit 102. Thanks!

**Comment by jackmoody11** [comment]
@statzhero Can you provide a company or two I can test this on?

**Comment by statzhero** [comment]
Yes CIK = 0001763799 -- but just FYI I have implemented this otherwise in the meantime.

**Comment by jackmoody11** [comment]
@statzhero I was looking through the filing types and it looks like we already have FilingType.FILING_ABSEE. Did you try using this and it didn't work as expected? If so, how did you fix it?

**Comment by jackmoody11** [comment]
@statzhero I tried this using the following code and was unable to find any bugs. Please let me know if this issue persists. Closing for now.

```python
from secedgar.filings import Filing, FilingType

filing = Filing(cik_lookup=["0001763799"], filing_type=FilingType.FILING_ABSEE)
filing.save("temp")
```
