### ISSUE TITLE
NetworkClient.get_response() calls requests.get() multiple times even on valid response

### ISSUE THREAD

**Issue by abbadata** [sec-edgar/sec-edgar#164]
In secedgar/client/network_client.py:

```
    def get_response(self, path, params, **kwargs):

        ...

        for i in range(self.retry_count + 1):
            response = requests.get(prepared_url, params=params, **kwargs)
            try:
                self._validate_response(response)
            except EDGARQueryError as e:
                # Raise query error if on last retry
                if i == self.retry_count:
                    raise e
            finally:
                time.sleep(self.pause)
        self.response = response
        return self.response
```

Even when the response passes validation, it does not break out of the for loop. Thus even on valid responses, requests,get() will be called multiple times (self.retry_count + 1). Thus, whenever we attempt to call save() on the filings, it makes a number of unnecessary network requests to Edgar.

**Comment by jackmoody11** [comment]
Thanks for pointing this out @abbadata! Would you like to create a PR for this? You should just need to add a break statement after validating the response. Otherwise, I can do it.

**Comment by jackmoody11** [comment]
TODO:

- [ ] Add whatsnew for v0.3.1
- [ ] Add test to check that `get_response` is only called as many times as is needed
- [ ] Release to PyPi
