### ISSUE TITLE
Larger filings hold back async from sending close to 10 requests per second

### ISSUE THREAD

**Issue by jackmoody11** [sec-edgar/sec-edgar#167]
**Describe the bug**
When trying to save a larger filing type (e.g. 10-K), only about 5 filings are being saved per second. This seems to suggest that maybe 10 requests aren't being sent per second. This seems to be related to the problem we were running into earlier, where there was some sort of latency between requests and the EDGAR server. Not sure if this is fixable or if it is a limitation out of this package's control.

**To Reproduce**
```python
from secedgar.filings import MasterFilings

m = MasterFilings(year=2020, quarter=4, entry_filter=lambda e: e.form_type == "10-K")
m.save('temp')
```

**Expected behavior**
Iterations per second should be closer to 10.

**Additional context**
 I know @reteps and I had discussed this earlier, but wanted to mention this in public in case anybody has a good solution or insight into why this problem is coming up.

**Comment by reteps** [comment]
https://github.com/sec-edgar/sec-edgar/blob/c6aad3b99fa186a42bf42de4c60a5bfc9efbdb81/secedgar/client/network_client.py#L200

Does this need to be `await`?

**Comment by reteps** [comment]
There is no reason it should be 5 it/sec. i was getting 10 on my own.

**Comment by reteps** [comment]
can we measure the time to save? I bet that's it.

**Comment by jackmoody11** [comment]
> https://github.com/sec-edgar/sec-edgar/blob/c6aad3b99fa186a42bf42de4c60a5bfc9efbdb81/secedgar/client/network_client.py#L200
> 
> Does this need to be `await`?

Not sure about that. Will need to check.

**Comment by jackmoody11** [comment]
> There is no reason it should be 5 it/sec. i was getting 10 on my own.

Hmmm...Yeah, we can do that.

**Comment by rahul18cracker** [comment]
Not sure why woudl you try a quater=4 for a 10-k form filed yearly. I use it like this 

my_filings = Filing(cik_lookup=ticker_symbol.lower(),
                    filing_type='10-K;',
                    count=10)
my_filings.save(self.__path_to_save_file)

This works good for me

Please note i am on version secedgar       0.1.7 which is very old as per current release number 

Thanks
~Rahul

**Comment by jackmoody11** [comment]
@rahul18cracker this is just referring to bulk downloading 10-K filings. So this would download all 10-k filings that were filed within the 3 month time period of the quarter.

**Comment by rahul18cracker** [comment]
@jackmoody11 : Thanks for the clarification, i dint notice this was a bulk call
