### ISSUE TITLE
Download just based on FilingType and not have a company?

### ISSUE THREAD

**Issue by alexiskattan** [sec-edgar/sec-edgar#170]
I'd like to download all the 10Ks between certain dates without specifying a stock.

```
my_filings = Filing(
    filing_type=FilingType.FILING_10K,
    start_date=datetime(2021, 1, 12),
    end_date=datetime(2021, 1, 14)
)
```

It seems to require a stock though.  When I run the above code, I get the error, `TypeError: __init__() missing 1 required positional argument: 'cik_lookup'`

My question is, is there anyway to search just based on the `FilingType` and not include a stock name?

**Comment by jackmoody11** [comment]
Hi @alexiskattan. You can use `MasterFilings` with an `entry_filter = lambda f: f.form_type.lower() == "10-k"` to do this. If you need to limit dates further, you can also check the documentation on how you can further modify `entry_filter`. We are currently working on changing the API to make this easier for users.

**Comment by alexiskattan** [comment]
Thank you!
