### ISSUE TITLE
tqdm needs to be added as a dependency 

### ISSUE THREAD

**Issue by alexiskattan** [sec-edgar/sec-edgar#175]
During a fresh install, you have to install `tqdm` independent.  Should probably be added as a dependency.

**Comment by jackmoody11** [comment]
Thanks for pointing this out @alexiskattan.

**Comment by Yugeshaidu** [comment]
Hi @jackmoody11 I would like to work on this issue. I'll have tqdm added as a dependency in the requirements.txt file

**Comment by jackmoody11** [comment]
> Hi @jackmoody11 I would like to work on this issue. I'll have tqdm added as a dependency in the requirements.txt file
> 
> 

Thanks @Yugeshaidu
