### ISSUE TITLE
Filing type 

### ISSUE THREAD

**Issue by mjkoo91** [sec-edgar/sec-edgar#181]
Hello!

First of all, I appreciate letting me use your crawler to download SEC filings. It has been very beneficial.
I was wondering if it is possible to add N-SAR filings (which are mutual fund annual reports) as a filing type ? They are largely used by academics and I believe they are as crucial as 10-K filings, as they are annual reports reported by open-end funds.
The name of the filing type is "NSAR-A" for annual report and "NSAR-B" for semi-annual. 
Please let me know if this is available. Thanks a lot!

**Comment by jackmoody11** [comment]
Hi @mjkoo91. Thanks for pointing this out. If you would like to create a pull request, this is relatively straightforward to do. All you need to do is go into the filing_types.py file and add two enums like the other filing types. It is in alphabetical order.
