### ISSUE TITLE
Does CIK_Lookup work with CIK numbers? 

### ISSUE THREAD

**Issue by meh369** [sec-edgar/sec-edgar#192]
I wanted to get filling data using CIK ids because they're more reliable and unique than using tickers which are constantly raising multiple matches error.

**Comment by jackmoody11** [comment]
See #190

**Comment by jackmoody11** [comment]
I am going to reopen this for issue tracking purposes since #190 is in discussions.

**Comment by jackmoody11** [comment]
@meh369 Were you able to get this to work?

**Comment by meh369** [comment]
> @meh369 Were you able to get this to work? If not, can you share an example of the issue you are facing? I think that #184 resolves this, but want to make sure.

@jackmoody11  Sure, this is the error that I get I am assuming it's the soup.find function that gives a NoneType error.
![cik2](https://user-images.githubusercontent.com/37578727/113831877-b1019100-97a5-11eb-870e-af659d592982.PNG)

**Comment by jackmoody11** [comment]
Fixed by #196.
