### ISSUE TITLE
Message Forbidden

### ISSUE THREAD

**Issue by meh369** [sec-edgar/sec-edgar#193]
Hi, 
I've tried other APIs for scrapping the sec fillings from the Edgar website however this has been the most stable one. However recently as of the 5th of April, I am facing a forbidden error message from the API. 

![secedgar](https://user-images.githubusercontent.com/37578727/113583397-391d5480-9647-11eb-90d7-e309f1bb7f90.PNG)

**Comment by jackmoody11** [comment]
@meh369 When was the first time you noticed this started happening? I am wondering if we need to start adding a header to our requests.

**Comment by meh369** [comment]
So up until Friday the queries were working fine and I was able to extract the fillings, I noticed this from today (Didn't try on weekends) all day the queries didn't work.

**Comment by jamiehannaford** [comment]
I'm also seeing this, seems to be quite recent.

**Comment by jackmoody11** [comment]
@jamiehannaford @meh369 can you try running your code on the most recent version from GitHub and let us know if it works now?

**Comment by jamiehannaford** [comment]
@jackmoody11 Yep, this works great. Thanks for the fix 👍
