### ISSUE TITLE
Skipping full submission download due to network error: 403 Client Error: Forbidden for url: https://www.sec.gov/Archives/edgar/data

### ISSUE THREAD

**Issue by knslee07** [sec-edgar/sec-edgar#199]
**Describe the bug**

I have been trying to download 10-Ks of all the companies. I see the 403 error for many of the requests.
This error occurs for several 10-Ks per tic and this error recurs for almost every tic.

**To Reproduce**
1. Go to '...'   dl.get("10-K", tic, include_amends=include_amends, download_details=false, amount=20)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16244893/114286103-7ad04580-9a21-11eb-92c9-813a304cc469.png)

**Desktop (please complete the following information):**
If specific to your OS, please specify which OS you are using [e.g. Windows, macOS, Ubuntu Linux, etc.]

Windows 10 64bit

**Additional context**

I only saw only a few 403 errors when downloading DEF-14As, so am not sure what makes difference between DEF 14A and 10-K.

**Comment by jackmoody11** [comment]
@knslee07 can you try passing a NetworkClient object with a user_agent?

Should look something like

```python
d = DailyFilings(..., client=NetworkClient(user_agent='My Company (my email)'))
```

**Comment by knslee07** [comment]
Thank you for your reply.

Since I was trying to download by cik, I used filing, not dailyfilings as follows:

my_filings = Filing(cik_lookup='aapl', filing_type=FilingType.FILING_10K, count=10, client=secedgar.client.NetworkClient(user_agent='company(email)'));
or
my_filings = Filing(cik_lookup='aapl', filing_type=FilingType.FILING_10K, start_date=datetime(2000, 1, 1), user_agent='My Firm')

These went through. But when I tried to save using .save, I get the runtimeError:

"RuntimeError: This event loop is already running"

**Comment by reteps** [comment]
The cursed error yet again

**Comment by pierrehenry14** [comment]
Got the same error.

**Comment by jackmoody11** [comment]
> The cursed error yet again

I think this has something to do with us not closing event loops or trying to create new loops when some are already running. The two things we should look at are how to use loop.close and how to use get_current_loop from asyncio.

**Comment by sunnyguan** [comment]
> @knslee07 can you try passing a NetworkClient object with a user_agent?
> 
> Should look something like
> 
> ```python
> d = DailyFilings(..., client=NetworkClient(user_agent='My Company (my email)'))
> ```

This worked for me using `Filing` with 10Q

**Comment by jackmoody11** [comment]
We need to add **kwargs to `DailyFilings` so that users don't have to directly deal with NetworkClient. We already have this for `MasterFilings` (soon to be named `QuarterlyFilings`). Should just be a matter of adding **kwargs to init and super init.

**Comment by jackmoody11** [comment]
> We need to add **kwargs to `DailyFilings` so that users don't have to directly deal with NetworkClient. We already have this for `MasterFilings` (soon to be named `QuarterlyFilings`). Should just be a matter of adding `**kwargs` to init and super init.

This is done now with #200.

**Comment by jackmoody11** [comment]
@knslee can you see if running 
```python
d = DailyFilings(..., user_agent='My Company (my email)')
``` 

fixes your issue?

**Comment by knslee07** [comment]
Yes, it fixes the 403 client error. Like I said, It give the loop error though.
