### ISSUE TITLE
Filing function end_date not defaulting to today?

### ISSUE THREAD

**Issue by miketsai05** [sec-edgar/sec-edgar#205]
The end_date behavior in Filing doesn't seem to be defaulting to today.

For example, when I run this:
```python
Filing(cik_lookup='aapl', 
       filing_type=FilingType.FILING_10Q, 
       start_date=datetime(2021, 2, 28), 
       end_date=datetime.today()).get_urls()
```

I get:
{'aapl': ['https://www.sec.gov/Archives/edgar/data/320193/000032019321000056/0000320193-21-000056.txt']}

Whereas if I run this 
```python
Filing(cik_lookup='aapl', 
       filing_type=FilingType.FILING_10Q, 
       start_date=datetime(2021, 2, 28)).get_urls()
```

I get an empty list back:
{'aapl': []}

I am using secedgar version 0.3.3 on windows 10 pro

**Comment by jackmoody11** [comment]
For the second filing, if you print out it's `end_date` property what do you get?

**Comment by jackmoody11** [comment]
This may be a network issue. From what I can tell, these two snippets create an object with the same attributes. If this issue persists, I would recommend trying out the v0.4.0-alpha version. Keep us updated if this issue remains. I will close this for now, as I assume it is a network issue.
