### ISSUE TITLE
Filings are not fetched when run inside a lambda function on AWS python runtime

### ISSUE THREAD

**Issue by ividamileen** [sec-edgar/sec-edgar#207]
We are trying to download filings for some companies and we constantly run into 403 errors from a week now. Below is the code that fails and error pasted. Any help greatly appreciated. Works on a MAC though. Only fails on Amazon Linux.

Code:
 
    my_filings = Filing(cik_lookup=cik,
                        filing_type=FilingType.FILING_10Q,
                        count=1,user_agent='###') #user agent should be MY NAME / COMPANY NAME (EMAIL ADDRESS)
    
    my_filings.save(download_path)

Error:

\Python\Python39\site-packages\secedgar\filings\filing.py:182: UserWarning: Only 0 of 1 filings were found for 1772704.
warnings.warn("Only {num} of {count} filings were found for {cik}.".format(
\Python\Python39\site-packages\secedgar\filings\filing.py:182: UserWarning: Only 0 of 1 filings were found for 1490349.
warnings.warn("Only {num} of {count} filings were found for {cik}.".format(
\Python\Python39\site-packages\secedgar\filings\filing.py:182: UserWarning: Only 0 of 1 filings were found for 1396440.
warnings.warn("Only {num} of {count} filings were found for {cik}.".format(
0%| | 0/40 [00:00<?, ?it/s]
Traceback (most recent call last):
…
my_filings.save(download_path)
File "\Python\Python39\site-packages\secedgar\filings\filing.py", line 226, in save
loop.run_until_complete(self.client.wait_for_download_async(inputs))
File "\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
return future.result()
File "\Python\Python39\site-packages\secedgar\client\network_client.py", line 235, in wait_for_download_async
await asyncio.gather(*tasks) # If results are needed they can be assigned here
File "\Python\Python39\site-packages\secedgar\client\network_client.py", line 211, in fetch_and_save
contents = await self.fetch(link, session)
File "\Python\Python39\site-packages\secedgar\client\network_client.py", line 199, in fetch
async with await session.get(link) as response:
File "\Python\Python39\site-packages\aiohttp\client.py", line 625, in _request
resp.raise_for_status()
File "\Python\Python39\site-packages\aiohttp\client_reqrep.py", line 1000, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://www.sec.gov/Archives/edgar/data/1370755/000156459021023642/0001564590-21-023642.txt')

**Comment by jackmoody11** [comment]
Are you running this across multiple nodes/machines? The only thing I can think of would be overusing the website.

**Comment by ividamileen** [comment]
Only running this on one machine and fetching 100 filings. I will try reducing requests per second.

**Comment by jackmoody11** [comment]
If you `pip install secedgar=0.4.0-alpha.1` are you able to get past this issue?

**Comment by jackmoody11** [comment]
Have you had a chance to try this again @ividamileen? I would like to close this if possible.

**Comment by ividamileen** [comment]
@jackmoody11 I stopped using this and implemented in house implementation due to time constraints. Thanks for your help!

**Comment by ividamileen** [comment]
The issue was with the user-agent header not sent correctly!
