### ISSUE TITLE
Error: Missing option '-u' / '--user-agent'

### ISSUE THREAD

**Issue by sroussey** [sec-edgar/sec-edgar#229]
**Describe the bug**

**To Reproduce**
pip install -r click secedgar==0.4.0-alpha.2

secedgar daily --date 20210723

Error: Missing option '-u' / '--user-agent'.

secedgar daily --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36" --date 20210723

Error: Missing option '-u' / '--user-agent'.

secedgar daily -u "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36" --date 20210723

Error: Missing option '-u' / '--user-agent'.

**Comment by jackmoody11** [comment]
Hey @sroussey do this:

```
secedgar -u "Your name (your email)" daily --date 20210723
```

The way we are currently doing it is passing the context before calling the commands. This reduces code duplication, but seems a bit counterintuitive. Can reconsider if this is confusing. Or can add to docs.

**Comment by sroussey** [comment]
Got it! Thanks!

**Comment by sroussey** [comment]
Is there an option to back off when we get aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests' ?

**Comment by jackmoody11** [comment]
> Is there an option to back off when we get aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests' ?

This isn't currently possible, but would be easy to add. Would just need to expose `NetworkClient` arguments to the [cli](https://github.com/sec-edgar/sec-edgar/blob/master/secedgar/cli.py).

**Comment by sroussey** [comment]
Ah. Does NetworkClient have an exponential backoff built in?

**Comment by jackmoody11** [comment]
> Ah. Does NetworkClient have an exponential backoff built in?

Yes, you can see [documentation here](https://github.com/sec-edgar/sec-edgar/blob/d88c7a331b2069dc399f0e752cd958cda1d278ae/secedgar/client.py#L29). This brings up another good point. I need to add more info about `NetworkClient` to the documentation.

**Comment by sroussey** [comment]
Oh, great! All those args should be in the cli.

**Comment by jackmoody11** [comment]
Can you help with that @sroussey?
