### ISSUE TITLE
message='Not Found', and the program stopped, how could I solve the problem?

### ISSUE THREAD

**Issue by liyifu0302** [sec-edgar/sec-edgar#231]
Hi everyone, 

I encountered the following problem when downloading 10K from sec edgar ->

"404, message='Not Found', url=URL('https://www.sec.gov/Archives/edgar/data/884219/0000884219-96-000033.txt')"

and then the program stopped.
Here is my code, did anyone encounter the same problem here?

```python
from secedgar.cik_lookup import get_cik_map
import nest_asyncio
from secedgar.filings import Filing, FilingType


nest_asyncio.apply()

cik_loop = dict(list(get_cik_map()["ticker"].items())[:])
cik_list = list(cik_loop)

for a, b in zip(range(0, len(cik_list), 50), range(50, len(cik_list), 50)):
      my_filings = Filing(cik_lookup = cik_list[a:b],
                      filing_type=FilingType.FILING_10K,
                      #count = 20,
                      user_agent='YOUR COMPANY NAME HERE')
      print(a,b)
      my_filings.save(r'E:\10K')
```

**Comment by jackmoody11** [comment]
@liyifu0302 thanks for reporting this. It looks like the error is on the SEC's side. You can see that this txt file is supposed to exist if you [look at this page on the SEC website](https://www.sec.gov/Archives/edgar/data/884219/000088421996000033/0000884219-96-000033-index.html). I am not exactly sure why this is happening. I would suggest adding a try and except block to take care of these cases.

This does bring up a good point though. That being that secedgar doesn't really provide a good way to handle these issues without having a good understanding of the code. I am not sure if callbacks to handle these sorts of errors will be easy to add, but I will look into it.

**Comment by liyifu0302** [comment]
> @liyifu0302 thanks for reporting this. It looks like the error is on the SEC's side. You can see that this txt file is supposed to exist if you [look at this page on the SEC website](https://www.sec.gov/Archives/edgar/data/884219/000088421996000033/0000884219-96-000033-index.html). I am not exactly sure why this is happening. I would suggest adding a try and except block to take care of these cases.
> 
> This does bring up a good point though. That being that secedgar doesn't really provide a good way to handle these issues without having a good understanding of the code. I am not sure if callbacks to handle these sorts of errors will be easy to add, but I will look into it.

Thx for your kindly reply! I have managed to find the company, it's “VVI”. It seems that there should be some problems in year 1996 for this company, skipping this company should fix this minor bug.
