### ISSUE TITLE
Cannot import name 'CompanyFilings'

### ISSUE THREAD

**Issue by dumrich** [sec-edgar/sec-edgar#232]
**Describe the bug**

**To Reproduce**
1. Install the `secedgar` with pipenv install secedgar
2. Copy the sample program on 
3. run `python test_edgar.py`

**Expected behavior**
Filings assigned to the my_filings variable

**Screenshots**
```
from secedgar import CompanyFilings, FilingType

my_filings = CompanyFilings(cik_lookup='aapl',
                            filing_type=FilingType.FILING_10Q,
                            count=15,
                            user_agent='Name (email)')
```

**Desktop (please complete the following information):**
I am on Artix Linux.

**Additional context**

**Comment by dumrich** [comment]
The exact error reads like this:
```
Traceback (most recent call last):
  File "test_edgar.py", line 1, in <module>
    from secedgar import CompanyFilings, FilingType
ImportError: cannot import name 'CompanyFilings'
```

**Comment by jackmoody11** [comment]
What version of secedgar are you using? You probably want to install the alpha version. `pip install secedgar==0.4.0a2`

**Comment by dumrich** [comment]
That solved it!
