### ISSUE TITLE
ImportError  

### ISSUE THREAD

**Issue by Thayyib786** [sec-edgar/sec-edgar#236]
**mportError                               Traceback (most recent call last)
<ipython-input-7-2aedf9560771> in <module>
----> 1 from secedgar import filings, FilingType
      2 
      3 # 10Q filings for Apple (ticker "aapl")
      4 my_filings = filings(cik_lookup="aapl",
      5                      filing_type=FilingType.FILING_10Q,

ImportError: cannot import name 'FilingType' from 'secedgar' (D:\ProgramData\Anaconda3\lib\site-packages\secedgar\__init__.py)

It throws up this error when I run the code below 

from secedgar import filings, FilingType

# 10Q filings for Apple (ticker "aapl")
my_filings = filings(cik_lookup="aapl",
                     filing_type=FilingType.FILING_10Q,
                     user_agent="Thayyib (thayyib@myamu.ac.in)")
my_filings.save('Desktop/Corporate Tax Planning')

**Comment by nhatkthanh** [comment]
Install the latest alpha version will fix this.  At the time of this writing, pip install secedgar==v0.4.0-alpha.2
