### ISSUE TITLE
Filing Type "CT ORDER"

### ISSUE THREAD

**Issue by jiapenghe1996** [sec-edgar/sec-edgar#237]
Hello,

Thank you for maintaining this incredible tool! I am wondering why the code doesn't support filing type "CT Order"? (see [https://www.sec.gov/edgar/searchedgar/ctorders.htm](url)). My apologies if I miss anything here.

Best,
Jacob

**Comment by jackmoody11** [comment]
@jiapenghe1996 you are right. We have an open PR that should solve this. I'll merge that into master. Thanks for bringing this to my attention!

**Comment by jiapenghe1996** [comment]
> @jiapenghe1996 you are right. We have an open PR that should solve this. I'll merge that into master. Thanks for bringing this to my attention!

Thank you!

**Comment by jiapenghe1996** [comment]
> @jiapenghe1996 you are right. We have an open PR that should solve this. I'll merge that into master. Thanks for bringing this to my attention!

This may or may not related to this Issue: do you know why the downloaded txt file for "CR Order" is garbled? (for example, https://www.sec.gov/Archives/edgar/data/1123979/999999999715000718/9999999997-15-000718.txt).

Thank you for reading my post.

**Comment by jackmoody11** [comment]
Hey @jiapenghe1996, looks like they are trying to include a PDF which shows up weird.

**Comment by jackmoody11** [comment]
Closed with #201
