### ISSUE TITLE
Download all filings for specific/multiple companies.

### ISSUE THREAD

**Issue by oerdem19** [sec-edgar/sec-edgar#241]
**Describe the bug**
I am trying to download all available files for a specific company or companies using the following code. 

```python
import secedgar as sec
from secedgar import filings, FilingType

# 10Q filings for Apple and Facebook (tickers "aapl" and "fb")
my_filings = filings(cik_lookup=["aapl"],
                    filing_type=None,
                    user_agent="xxx (XXX")
my_filings.save("/mnt/f/SECCIKs")
```
Returns: 

AttributeError: 'NoneType' object has no attribute 'value'

**To Reproduce**

**Expected behavior**
Saving of all files for a specific company/multiple companies.

**Comment by jackmoody11** [comment]
You need to specify which filing type you want to get (for example, `filing_type=FilingType.FILING_10Q`).
