### ISSUE TITLE
13F-HR/A Files are downloaded with filing_type=FilingType.FILING_13FHR

### ISSUE THREAD

**Issue by MineSafety** [sec-edgar/sec-edgar#244]
**Describe the bug**

Using `filing_type=FilingType.FILING_13FHR` seems to include _both_ 13F-HR and 13F-HR/A files. Expectation would be that it _only_ downloads 13F-HR files, and not the amended filings. 

**To Reproduce**
```
from secedgar import CompanyFilings, FilingType

filings_13f = CompanyFilings(cik_lookup=ciks,
                            filing_type=FilingType.FILING_13FHR)
filings_13f.save('filings', skip_downloaded=True)
```
Notice how both 13F-HR and 13F-HR/A files are downloaded to the `/filings/{cik}/13F-HR/` folder. Whereas if you were to use `filing_type=FilingType.FILING_13FHR_AMEND`, the amended filings would get downloaded to the `/filings/{cik}/13F-HR/A` directory instead. 

**Expected behavior**

Should only download 13F-HR filings. To download only 13F-HR/A filings, I would imagine—at least according to the documentation—you would have to instead use 
```
filings_13f_amend = filings_13f = CompanyFilings(cik_lookup=ciks,
                            filing_type=FilingType.FILING_13FHR_AMEND)
filings_13f_amend.save('filings', skip_downloaded=True)

```

**Comment by jackmoody11** [comment]
@MineSafety yes, this is a bug. We need to filter so that those results aren't considered when fetching data. Just reopened #154.
