### ISSUE TITLE
Form 4 Parser

### ISSUE THREAD

**Issue by darrion** [sec-edgar/sec-edgar#253]
**Is your feature request related to a problem? Please describe.**
Insider trading information has become a hot commodity for retail investors. The parser does not currently extract pertinent data on buying and selling of securities by insiders.

**Describe the solution you'd like**
Add a function to the parser to extract non-derivative transaction information pertinent to retail investors intending to track trades of insiders.

**Describe alternatives you've considered**
All other alternatives are closed-source/proprietary and paid.

**Additional context**
No additional context.

**Comment by jackmoody11** [comment]
Looks like you have already started working on this @darrion. If you create a PR, I can review.
