### ISSUE TITLE
Is this comaptible with python 3.10 ?

### ISSUE THREAD

**Issue by 1-Harshit** [sec-edgar/sec-edgar#265]
**Describe the bug**
I am getting import error over and over again while working with this package.

**To Reproduce**
1. using Python 3.10.2 (pip 22.0.3)
2. use venv
3. pip install
4. paste the demo code from the documentation 

**Expected behavior**
Import error 

**Desktop (please complete the following information):**
I am on manjaro linux 5.15.25-1-MANJARO

**Comment by jackmoody11** [comment]
See #236. The current documentation is for the code in alpha.

**Comment by 1-Harshit** [comment]
Thanks!
