### ISSUE TITLE
Unclear error during downloading data

### ISSUE THREAD

**Issue by Mr-S-Mirzoev** [sec-edgar/sec-edgar#266]
**Describe the bug**
Unclear error during using filings.save()

**To Reproduce**
During using the library as follows:
`my_filings = filings(cik_lookup="V",
                     filing_type=FilingType.FILING_10K,
                     user_agent="email@gmail.com",)
my_filings.save(".")`

 I'm experiencing the following error:
 ----> 5 my_filings.save(".")

9 frames
[/usr/lib/python3.7/json/decoder.py](https://localhost:8080/#) in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I'm suspecting that there has been a rate abuse from my side, but it's definitely not clear from the exception

**Expected behavior**
I would expect an exception with response from server as description

**Desktop (please complete the following information):**
Colab Linux node

**Comment by kuatroka** [comment]
Just in case, recreate this on your local machine and see if you still get the same error. I had a similar experience with Colab but using a different library to download the SEC data. Once moved to the local environment, all went ok

**Comment by jackmoody11** [comment]
@Mr-S-Mirzoev have you tried this outside of Colab?

**Comment by Ccongggg** [comment]
did you solve this problem ?

**Comment by jackmoody11** [comment]
Closing this since we don't have more info. It could have been due to user_agent not being passed to `get_cik_map` on our side. This is fixed in the most recent dev version. If you still face this issue after pip installing the development version, feel free to reopen.
