### ISSUE TITLE
ComboFilings lambda bug when QuarterlyFilings called

### ISSUE THREAD

**Issue by agraddy** [sec-edgar/sec-edgar#269]
**Describe the bug**
When ComboFilings uses QuarterlyFilings, it includes a lamba in two different locations that is causing an error:
https://github.com/sec-edgar/sec-edgar/blob/master/secedgar/core/combo.py#L169
https://github.com/sec-edgar/sec-edgar/blob/master/secedgar/core/combo.py#L186

Those lines say:
```
lambda x: date(x['date_filed']) >= self.start_date))
```
And
```
lambda x: date(x['date_filed']) <= self.end_date))
```

This is causing an error that says:
> TypeError: tuple indices must be integers or slices, not str

I believe this is what those lines should say:
```
lambda x: datetime.strptime(x.date_filed, '%Y-%m-%d').date() >= self.start_date))
```
And
```
lambda x: datetime.strptime(x.date_filed, '%Y-%m-%d').date() <= self.end_date)) 
```

**To Reproduce**
```
from datetime import date
from secedgar import ComboFilings

filings = ComboFilings(start_date=date(2022, 2, 28),
                     end_date=date(2022, 4, 15),
                     user_agent="Your name (your email)")
filings.save('./sec-import')
```

**Expected behavior**
Should run without errors.

**Comment by jackmoody11** [comment]
Thanks for pointing this out! Just created PR and will merge and create a new patch once CI gives the ok.
