### ISSUE TITLE
CIK to TICKER and CUSIP to TICKER mapping

### ISSUE THREAD

**Issue by kuatroka** [sec-edgar/sec-edgar#271]
It's more of a question than a feature request.
Does anybody know of a possible logic/conceptual process or an actual module that would take a CIK and much more importantly CUSIP and convert it to a corresponding TICKER? At least for US market?

**Comment by jackmoody11** [comment]
Does this help?

http://rankandfiled.com/#/data/cusips

**Comment by kuatroka** [comment]
Thanks Jack. It seems to be exactly what I'm after
