### ISSUE TITLE
ImportError: cannot import name 'FilingType' from 'secedgar' (/usr/local/lib/python3.7/dist-packages/secedgar/__init__.py)

### ISSUE THREAD

**Issue by gautambak** [sec-edgar/sec-edgar#272]
**Describe the bug**

**To Reproduce**
in google colab follow the steps on the site:
!pip install secedgar 
from secedgar import filings, FilingType

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
If specific to your OS, please specify which OS you are using [e.g. Windows, macOS, Ubuntu Linux, etc.]

**Additional context**

**Comment by gautambak** [comment]
Note it works if I do this:
!pip install secedgar==0.4.0a2

**Comment by jackmoody11** [comment]
Duplicate of #236
