### ISSUE TITLE
AttributeError: module 'async_timeout' has no attribute 'Timeout'

### ISSUE THREAD

**Issue by agdownes** [sec-edgar/sec-edgar#273]
when running the demo code:

from secedgar import FilingType, filings

my_filings = filings(cik_lookup="AAPL",
                     filing_type=FilingType.FILING_10K,
                     user_agent="Name name@me.com")
my_filings.save('/home/tony/Downloads/sec_test/')

secedgar 0.4.0a3
async-timeout 3.01

**Comment by agdownes** [comment]
Issue seems to be aiohttp requires async-timeout >=4 but secedgar requires async-timeout <4

**Comment by jackmoody11** [comment]
See #263
