### ISSUE TITLE
 secedgar 0.4.0a2 requires async-timeout<4.0,>=3.0, but you have async-timeout 4.0.2 which is incompatible.

### ISSUE THREAD

**Issue by rahul18cracker** [sec-edgar/sec-edgar#281]
**Describe the bug**
I was trying to do a `pip install Redis` when i see the error for async-timeout being greater than 4.0. I refered to this #263  and upgraded the aiohttp and sec edgar to 0.4.0a2. But now i see a different error 

```console 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
secedgar 0.4.0a2 requires async-timeout<4.0,>=3.0, but you have async-timeout 4.0.2 which is incompatible.
```
I thought after upgrading to 0.4.0a2 this need to downgrade asyn-timeout would not be there. Can you please let me know the correct combination with Redis ?

My pip list 
```console
Package            Version
------------------ -----------
aiohttp            3.8.1
aiosignal          1.2.0
amqp               5.1.1
async-timeout      4.0.2
attrs              21.4.0
beautifulsoup4     4.11.1
billiard           3.6.4.0
celery             5.2.7
certifi            2022.5.18.1
chardet            3.0.4
charset-normalizer 2.0.12
click              8.1.3
click-didyoumean   0.3.0
click-plugins      1.1.1
click-repl         0.2.0
Deprecated         1.2.13
flake8             4.0.1
Flask              2.1.2
frozenlist         1.3.0
idna               3.3
importlib-metadata 4.11.4
iniconfig          1.1.1
itsdangerous       2.1.2
Jinja2             3.1.2
kombu              5.2.4
lxml               4.8.0
MarkupSafe         2.1.1
mccabe             0.6.1
multidict          6.0.2
packaging          21.3
pip                20.3.4
pkg-resources      0.0.0
pluggy             1.0.0
prompt-toolkit     3.0.30
py                 1.11.0
pycodestyle        2.8.0
pyflakes           2.4.0
pymongo            4.1.1
pyparsing          3.0.9
pytest             7.1.2
pytz               2022.1
redis              4.3.4
requests           2.27.1
secedgar           0.4.0a2
setuptools         44.1.1
six                1.16.0
soupsieve          2.3.2.post1
tomli              2.0.1
tqdm               4.64.0
typing-extensions  4.2.0
urllib3            1.26.9
vine               5.0.0
wcwidth            0.2.5
Werkzeug           2.1.2
wheel              0.34.2
wrapt              1.14.1
yarl               1.7.2
zipp               3.8.0 
```

**To Reproduce**
1. Just install the requirements and it will pop up with the error 

**Expected behavior**
I should not see any dependency faults from pip 

**Screenshots**
NA

**Desktop (please complete the following information):**
```console 
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
```

**Additional context**
This is me just trying to get Celery working with Redis and Flask

**Comment by rahul18cracker** [comment]
@varunpan : I am sorry for the late response, can you please clarify a bit more ?
1. You downloaded the sec edgar repo 
2. then you removed the restriction, can you please clarify where did you remove this restriction from ? file pointer or diff's would be helpful 

Few more questions: 
1. What will happen when you upgrade secedgar ?

@jackmoody11 
1. Can you please comment here is this is the correct approach ?
2. If not how to get around this problem ?

**Comment by jackmoody11** [comment]
Going to close given that this was for an old version. If the problem persists with the newest version, please raise the issue again.
