### ISSUE TITLE
Create a basic command line interface.

### ISSUE THREAD

**Issue by npsolve** [sec-edgar/sec-edgar#33]

**Comment by jackmoody11** [comment]
I can help with this enhancement. If you wouldn't mind leaving some basic functionality you would like to see, I can work on it.

**Comment by coyo8** [comment]
Sure @jackmoody11. You can check for [click](https://click.palletsprojects.com/en/7.x/). It is really a good wrapper to write CLI tools.

**Comment by jackmoody11** [comment]
It might be best to focus on the main functionality before we add a CLI.
