### ISSUE TITLE
Asynchronous requests.

### ISSUE THREAD

**Issue by npsolve** [sec-edgar/sec-edgar#38]
Currently, sec-edger download one file at a time which is too slow as a user experience. We can have asynchronous requests to make it faster.

**Comment by jackmoody11** [comment]
Not sure if SEC rate limits, but even if they do we can work around it to make this happen.

**Comment by jackmoody11** [comment]
This is going to be really important if we want to provide access to lots of reports at once. Is there a way to do this for Python 2.7 and Python 3.x? Looks like the newest version of aiohttp requires Python 3.5.3+

**Comment by coyo8** [comment]
I did some reading. I will add an example. We can simply use `async/await`.  Our code structure will change as now we will get callbacks. Trying to write a wrapper on top of request.

**Comment by jackmoody11** [comment]
@coyo8 can you look at #85?

**Comment by jackmoody11** [comment]
Should we make support require 3.5? If we did this, we would be to just use the async/await syntax.

**Comment by reteps** [comment]
Status @npsolve?

**Comment by jackmoody11** [comment]
@reteps I am not very familiar with the async await syntax, so this has not gone very far.
