### ISSUE TITLE
What Python versions should we support?

### ISSUE THREAD

**Issue by jackmoody11** [sec-edgar/sec-edgar#85]
Currently we support Python 2.7, and 3.4-3.8. If we want to add async support, we can easily do so using aiohttp (which only supports 3.5.3 and older) and the async/await syntax added in 3.5. Since we are currently building the package, is there any good reason to add support for older versions of Python? Or should we develop for newer versions of Python?

**Comment by coyo8** [comment]
I think we should switch to a new version as python 2 is already going to be depreciated but we will have to evaluate the effort in migration.

**Comment by jackmoody11** [comment]
@coyo8 right now all tests are running fine for the supported versions of Python 3. I think this should be as simple as updating the docs to say that only Python 3 is supported.

**Comment by jackmoody11** [comment]
As of now, we have decided to stop supporting Python 2, as it has reached its end of life. Looking forward to async support and using aiohttp, we will support Python 3.5+. Please let us know if this poses challenges for you and we will reconsider.
